server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cyberpunk_combat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${dbUser}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect